### PR TITLE
add queen-red to links

### LINKED ISSUE #62: Add accent color to markdown links
The markdown styled by tailwind has a plain styling.
The pages would look more vibrant if the links had the same "queen-red" color
used on the homepage.
Screen Shot 2021-12-24 at 19 01 56

### PR DESCRIPTION
**Pull request by inezabonte**
fixes #62 
Screen Shot 2022-02-02 at 19 19 27

### CODE REVIEW

**Review by raae — APPROVED** [review]

**Comment by raae** [comment]
If you are allowed, merge away!

**Comment by inezabonte** [comment]
I don't have the permission to @raae

**Comment by raae** [comment]
Seems like it is not building...

**Comment by inezabonte** [comment]
I just tried building locally and I came across this error
Screen Shot 2022-02-03 at 16 10 10
.

**Pull request merged**
